---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Tools and Techniques for Data Science</h1>
<h1 align="center">Course: Deep Learning</h1>

---
<h1 align="right">Muhammad Sheraz (Data Scientist)</h1>
<h1 align="center">Day 16 (Back Propagation Classification Keras)</h1>


<img   src="../Images/nlp-approaches2.png"  >


# <b>1 <span style='color:#0edd57c9'>|</span> Back Propagation Algorithim</b>

<img src="../Images/propagationmain.png"  style="width: 100%;">


In [6]:
import numpy as np
import pandas as pd

In [12]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])

In [13]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [14]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [15]:
model=Sequential()

model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.get_weights()

[array([[-0.59916115,  1.0215029 ],
        [ 0.7222793 ,  0.12174499]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.20012403],
        [-0.22382808]], dtype=float32),
 array([0.], dtype=float32)]

In [18]:
new_weights=[np.array([[0.1,0.1],
                       [0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [19]:
model.set_weights(new_weights)

In [20]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [27]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6920
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6920
Epoch 3/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6921
Epoch 4/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6922
Epoch 5/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6920
Epoch 6/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6919
Epoch 7/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6920
Epoch 8/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6920
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6920
Epoch 10/50
4/4 [==============================] - 0s 5ms/step - loss: 0.6921
Epoch 11/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6919
Epoch 12/50
4/4 [==============================] - 0s 4ms/step - loss: 0.6921
Epoch 13/50
4/4 [==============================] - 0s 4ms/step - loss: 0.

In [28]:
model.get_weights()

[array([[0.1199335 , 0.1199335 ],
        [0.05949751, 0.05949751]], dtype=float32),
 array([-0.10433333, -0.10433333], dtype=float32),
 array([[0.08238374],
        [0.08238374]], dtype=float32),
 array([-0.04462083], dtype=float32)]