# <b>1 <span style='color:#0edd57c9'>|</span> Back Propagation Algorithim</b>

<img src="../Images/propagationmain.png"  style="width: 100%;">


In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()

[array([[0.77433133, 0.2740178 ],
        [0.28804266, 1.078322  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.21713042],
        [ 0.48922074]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights=[np.array([[0.1,0.1],
                       [0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75

4/4 [==============================] - 2s 11ms/step - loss: 27.8898
Epoch 2/75
4/4 [==============================] - 0s 6ms/step - loss: 27.5918
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2448
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 26.8998
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 26.5824
Epoch 6/75
4/4 [==============================] - 0s 7ms/step - loss: 26.2195
Epoch 7/75
4/4 [==============================] - 0s 5ms/step - loss: 25.8409
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4617
Epoch 9/75
4/4 [==============================] - 0s 5ms/step - loss: 25.0621
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 24.6860
Epoch 11/75
4/4 [==============================] - 0s 11ms/step - loss: 24.2440
Epoch 12/75
4/4 [==============================] - 0s 5ms/step - loss: 23.8123
Epoch 13/75
4/4 [==============================] - 0s 7ms/

In [13]:
model.get_weights()

[array([[0.37373608, 0.37373608],
        [0.36550543, 0.36550543]], dtype=float32),
 array([0.27232358, 0.27232358], dtype=float32),
 array([[0.37290594],
        [0.37290594]], dtype=float32),
 array([0.204711], dtype=float32)]